### ISSUE TITLE
Initialize is not implemented on object in visual works

### ISSUE THREAD

**Issue by VincentBlondeau** [ObjectProfile/Pharo2VW#6]
It may be better to use an intermediate class that implement this concept.
It is not conceivable to add it on Smalltalk.Object as it may break some existing source code

**Comment by akevalion** [comment]
In this case exporter has an optional operation `#addInitializerToSuperclasses: bool` this allows to exporter add a new method:
```Smalltalk
new
   ^ super new initialize.
```
For superclasses in the exported classes, only if this method is not defined in the exported class.
